version: '3.5'
services:
  node-app:
    image: rafaelcarreira/node-app:1.1
    deploy:
      mode: global
   #ports:
    #  - "3000:3000"
    #deploy:
    #  replicas: 5

  nginx:
    image: rafaelcarreira/nginx-stack:1.0
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    depends_on:
      - node-app
    volumes:
      - NGINX_LOGS:/var/log/nginx
      - NGINX_CERTS:/etc/letsencrypt
    environment:
#      - CERTBOT_DOMAIN=rafael-vdvx.localhost.run
#      - CERTBOT_MAIL=rafel747@gmail.com
      - SSMTP_EMAIL=rafel747@gmail.com
      - SSMTP_HOST=smtp.gmail.com:465
      - SSMTP_TLS=YES
      - SSMTP_TOEMAIL=rafael.s.carreira@gmail.com
#      - SSMTP_PASSWORD=password

   #configs:
   #   - source: NGINX_NODE
   #     target: /etc/nginx/nginx.conf


volumes:
  NGINX_LOGS:
  NGINX_CERTS:
#configs:
#  NGINX_NODE:
#    external: true
